/**
 * Official report preview — the shared shell used by every generated
 * report: letterhead, generation metadata, filter summary chips, the
 * report body and a footer.
 */

import type { ReportMeta } from "@/lib/reports/report-utils";

export function ReportPreview({
  title,
  meta,
  filterSummary,
  children,
}: {
  title: string;
  meta: ReportMeta;
  filterSummary: Record<string, string>;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-card border border-line bg-white">
      {/* Letterhead */}
      <div className="flex flex-wrap items-start justify-between gap-4 border-b border-line bg-forest-50/50 px-5 py-4">
        <div>
          <p className="text-sm font-bold tracking-wide text-forest-900">NSTR PATROL</p>
          <p className="mt-1 text-base font-semibold text-ink">{title}</p>
          <p className="text-xs text-ink-soft">
            Forest &amp; Wildlife Division · Integrated Forest Management
          </p>
        </div>
        <div className="text-right text-xs text-ink-soft">
          <p>
            Generated by{" "}
            <span className="font-medium text-ink">{meta.generatedBy}</span>
            {meta.generatedByDesignation ? ` (${meta.generatedByDesignation})` : ""}
          </p>
          <p>{meta.generatedAt}</p>
        </div>
      </div>
      {/* Filter summary */}
      <div className="flex flex-wrap gap-1.5 border-b border-line px-5 py-3">
        {Object.entries(filterSummary).map(([label, val]) => (
          <span
            key={label}
            className="rounded-full bg-forest-50 px-2.5 py-0.5 text-[11px] font-medium text-forest-800"
          >
            {label}: {val}
          </span>
        ))}
      </div>
      {/* Body */}
      <div className="space-y-5 px-5 py-4">{children}</div>
      {/* Footer */}
      <div className="border-t border-line px-5 py-3 text-center text-[11px] text-ink-faint">
        Generated from the NSTR Patrol portal · Forest Department · For official use
      </div>
    </div>
  );
}

export function ReportSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h3 className="mb-2 border-b border-line pb-1 text-[11px] font-semibold uppercase tracking-wide text-ink-soft">
        {title}
      </h3>
      {children}
    </section>
  );
}

/** Compact report stat tile (lighter than the dashboard KpiCard). */
export function ReportStat({
  label,
  value,
  sub,
}: {
  label: string;
  value: string | number;
  sub?: string;
}) {
  return (
    <div className="rounded-card border border-line bg-white p-3">
      <p className="text-[11px] font-medium uppercase tracking-wide text-ink-faint">{label}</p>
      <p className="mt-1 text-xl font-semibold tracking-tight text-ink">{value}</p>
      {sub && <p className="mt-0.5 text-xs text-ink-soft">{sub}</p>}
    </div>
  );
}